* libsqlite3x is now made by autotools instead of custom makefile   * its Shake'N'Make didn't work in MinGW * sqlite3 is now recognized by autoconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4489,11 +4489,76 @@ echo "$as_me: error: Could not link against $ax_lib !" >&2;}
 	fi
 
 
+{ echo "$as_me:$LINENO: checking for main in -lsqlite3" >&5
+echo $ECHO_N "checking for main in -lsqlite3... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sqlite3_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsqlite3  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sqlite3_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sqlite3_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sqlite3_main" >&5
+echo "${ECHO_T}$ac_cv_lib_sqlite3_main" >&6; }
+if test $ac_cv_lib_sqlite3_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBSQLITE3 1
+_ACEOF
+
+  LIBS="-lsqlite3 $LIBS"
+
+fi
+
+
 ## create a config.h file (Automake will add -DHAVE_CONFIG_H)
 #AC_CONFIG_SRCDIR([src/libgetodo/getodo.cpp])
 #AC_CONFIG_HEADER([config.h])
 
-ac_config_files="$ac_config_files Makefile lib/Makefile src/Makefile src/libgetodo/Makefile src/getodogui/Makefile src/test/Makefile src/test/test1-sql/Makefile"
+ac_config_files="$ac_config_files Makefile lib/Makefile lib/sqlite3x/Makefile src/Makefile src/libgetodo/Makefile src/getodogui/Makefile src/test/Makefile src/test/test1-sql/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -5097,6 +5162,7 @@ do
     "depfiles") CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "lib/Makefile") CONFIG_FILES="$CONFIG_FILES lib/Makefile" ;;
+    "lib/sqlite3x/Makefile") CONFIG_FILES="$CONFIG_FILES lib/sqlite3x/Makefile" ;;
     "src/Makefile") CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
     "src/libgetodo/Makefile") CONFIG_FILES="$CONFIG_FILES src/libgetodo/Makefile" ;;
     "src/getodogui/Makefile") CONFIG_FILES="$CONFIG_FILES src/getodogui/Makefile" ;;
